Project cost
lablivre-unb/tais pull request #215
Opened 2018-10-29 21:03 UTC by MatheusMiranda

related to issue #187

2018-10-30 15:33 UTC, MatheusFaria requested changes
acho que falta a data

2018-10-30 15:33 UTC, MatheusFaria commented on web/tais/templates/_default.html
> +			<h5>Em X/11/2018:</h5>
`X/11` ?

2018-10-30 15:37 UTC, MatheusFaria commented
No geral a usabilidade não esta boa, depois de fazer uma pergunta e ela responder, seria bom ter um `Você gostaria de saber mais?` ou `Quer saber mais detalhes sobre X?`, porque parece que ela parou de responder e espera mais perguntas gerais.

@palomacmamede pode dar uma olhada nisso com o pessoal?

2018-10-31 19:33 UTC, MatheusMiranda commented
Neste PR também foram alteradas os seguintes testos de `utters`:

**utter_curiosidades_mais:**
**Texto antigo:** Gostaria de saber mais curiosidades? (Sim ou Não)
**Texto novo:** Gostaria de saber mais sobre outras curiosidades? (Sim ou Não)
 
**utter_curiosidades_lei_rouanet_denuncia:**
**Texto antigo:** Em caso de dúvida, entrar em contato com as áreas do MinC, http://rouanet.cultura.gov.br/fale-conosco/ .
**Texto novo:** Para entender como fazer uma denúncia, entre em contato com as áreas do MinC: http://rouanet.cultura.gov.br/fale-conosco/ .

2018-10-31 19:34 UTC, merged