Interaction Improvements
lablivre-unb/tais pull request #401
Opened 2019-04-03 14:33 UTC by palomacmamede

Melhorias na Utter_Tudo_Bem
Melhorias de interação: Agora a TAIS ensina o usuário a conversar com ela com a #MEAJUDA

2019-04-08 13:41 UTC, RochaCarla commented
Inserir o texto da utter no fallback policy  e retirar as stories mapeadas

2019-04-10 12:50 UTC, LeoSilvaGomes-zz requested changes
@palomacmamede

2019-04-10 12:50 UTC, LeoSilvaGomes-zz commented on bot/domain.yml
> +          Mas podemos continuar conversando sobre alguns conceitos básicos da lei Rouanet (:
Ao tentar treinar a Tais, há um erro nessa parte do código mediante a carinha "(:", pois dois pontos se refere a sintaxe de tópicos. Por isso sente-se necessidade de mudança nessa parte.

![image](https://user-images.githubusercontent.com/38738836/55846519-541e6200-5b1c-11e9-9949-830da7de0cd3.png)

2019-04-10 12:52 UTC, palomacmamede commented on bot/domain.yml
> +          Mas podemos continuar conversando sobre alguns conceitos básicos da lei Rouanet (:
Vou editar agora (:

2019-04-10 13:21 UTC, LeoSilvaGomes-zz approved these changes

2019-04-10 13:21 UTC, merged