Backup de visualizações e dashboards
lablivre-unb/tais pull request #440
Opened 2019-04-15 19:17 UTC by brunapinos

Esse PR tem como objetivo adicionar um arquivo chamado `export.json`, que contem as visualizações construidas até hoje para o bot. Isto ajuda aqueles que queriam usar seus próprio dados de desenvolvimento a ter um esqueleto de visualizações.

A descrição de como utilizar este backup está no README.md

Associada a issue #411

2019-04-16 12:57 UTC, arthurTemporim requested changes
Quando eu executei as instruções do README usando o arquiv `export.json` apareceu uma página de erro. Além disso os `dashboards` aparentemente foram gerados, porém não foram adicionadods na aba de `dashboards`. Pode resolver isso?

2019-04-16 12:57 UTC, arthurTemporim commented on README.md
> +* Utilize o arquivo `dashboard.json` na pasta `\elasticsearch` do projeto.
O arquivo `dashboard.json` não existe na paste `\elasticsearch`, deveria ser `export.json`?

Troca a posição da barra de `\elasticsearch` para `elasticsearch/`.

2019-04-22 15:02 UTC, guilacerda commented
Quando estava subindo para testar o PR, deu um problema de que os indices estavam fechados, com isso não conseguia subir o Kibana. Não é um erro do PR, mas do próprio pc. Mas que deve ser lembrado em algum momento pra pessoa conferir se os indices do elastic estão open ou não

2019-04-22 15:02 UTC, guilacerda approved these changes

2019-04-22 15:05 UTC, arthurTemporim approved these changes

2019-04-22 16:57 UTC, merged